#!/usr/bin/env bash

function echo_ok() { echo -e '\033[1;32m'"$1"'\033[0m'; }
function echo_warn() { echo -e '\033[1;33m'"$1"'\033[0m'; }
function echo_error() { echo -e '\033[1;31mERROR: '"$1"'\033[0m'; }

dotfiles_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo_ok "Install starting. You may be asked for your password (for sudo)."

# Homebrew
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
if hash brew &>/dev/null; then
	echo_ok "Homebrew already installed. Getting updates..."
	brew update
	brew doctor
else
	echo_warn "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# Basic tools
brew install \
  git \
  bash bash-completion bash-git-prompt \
  curl openssl \
  htop \
  cask \
  ansible \
  postgresql@15

# Neovim
brew install lua lua-language-server
brew install neovim --HEAD
npm install -g vim-language-server

# Modern unix tools
brew install ripgrep fd exa fzf jq

# Kubernetes
brew install kubectl k9s stern

# Languages
brew install \
  ctags \
  node \
  rbenv \
  fnm \
  go gopls

# Fonts
brew tap homebrew/cask-fonts

FONTS=(
  font-roboto
  font-fira-code
  font-cascadia-code
  font-jetbrains-mono
  font-iosevka
  font-fantasque-sans-mono
  font-monoid
  font-fira-code-nerd-font
  font-jetbrains-mono-nerd-font
  font-iosevka-nerd-font
  font-droid-sans-mono-nerd-font
  font-fantasque-sans-mono-nerd-font
  font-monoid-nerd-font
)

brew install --cask "${FONTS[@]}"

# Applications
brew install --cask \
  iterm2 \
  obsidian \
  yandex-disk \
  keepassxc \
  firefox \
  yandex-browser \
  slack \
  telegram-desktop \
  syncthing \
  vlc \
  shadowsocksx-ng

brew cleanup

# Keyboard settings
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

echo_ok "Osx setup complete"
