#!/usr/local/bin/bash

  function echo_ok() { echo -e '\033[1;32m'"$1"'\033[0m'; }
  function echo_warn() { echo -e '\033[1;33m'"$1"'\033[0m'; }
  function echo_error() { echo -e '\033[1;31mERROR: '"$1"'\033[0m'; }

# Install all packages required for modern development (kind of)

dotfiles_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo_ok "Install starting. You may be asked for your password (for sudo)."

# homebrew
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
if hash brew &>/dev/null; then
	echo_ok "Homebrew already installed. Getting updates..."
	brew update
	brew doctor
else
	echo_warn "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew install neovim

brew install \
  bash bash-completion bash-git-prompt \
  git git-delta \
  curl htop openssl \
  ctags \
  ripgrep fd exa fzf jq \
  node \
  rbenv fnm \
  kubectl k9s stern \
  antibody \
  cask \
  ansible \
  postgresql

# cool developer fonts
brew tap homebrew/cask-fonts

FONTS=(
  font-roboto
  font-fira-code
  font-cascadia-code
  font-jetbrains-mono
  font-iosevka
  font-droid-sans-mono
  font-fantasque-sans-mono
  font-monoid
  font-fira-code-nerd-font
  font-cascadia-code-nerd-font
  font-jetbrains-mono-nerd-font
  font-iosevka-nerd-font
  font-droid-sans-mono-nerd-font
  font-fantasque-sans-mono-nerd-font
  font-monoid-nerd-font
)

brew install --cask "${FONTS[@]}"

# OSX apps
brew install iterm2 vimr

brew cleanup

echo_ok "Fonts installed"
echo_ok "OSX setup complete"
